apiVersion: v1
kind: Pod
metadata:
  name: my-app
  namespace: ns-app
  labels:
    name: my-app
    app: employees
    owner: trupal
spec:
  containers:
    - name: my-app
      image: 120587352063.dkr.ecr.us-east-1.amazonaws.com/my_app:v1
      ports:
        - containerPort: 8080
      env:
        - name: DBHOST
          value: "10.244.0.13" #needs updating according to pod ip of the DB
        - name: DBPORT
          value: "3306"
        - name: DBUSER
          value: "root"
        - name: DATABASE
          value: "employees"
        - name: DBPWD
          value: "P@ssw0rd"
