apiVersion: v1
kind: Service
metadata:
  name: my-db
  namespace: ns-db
  labels:
    owner: trupal
    servicetype: clusterip
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
