apiVersion: v1
kind: Pod
metadata:
  name: my-db
  namespace: ns-db
  labels:
    name: my-db
    app: mysql
    owner: trupal
spec:
  containers:
    - name: my-db
      image: 120587352063.dkr.ecr.us-east-1.amazonaws.com/my_db:v1
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "P@ssw0rd"
